### ISSUE TITLE
Donate/Add confusion?

### ISSUE THREAD

**Issue by reidrankin** [thorchain/docs#27]
It looks to me like https://github.com/thorchain/thornode/commit/028518fef755b59af1a2d067e56982e031e9f1c4 renamed "DONATE" to "ADD", but developers/transaction-memos.md still says that on multi-chain "ADD" will give you a stake in the pool. What's right?

**Comment by thorchain-admin** [comment]
ADD will add liquidity and give you ownership
DONATE will donate liquidity to the pool and *not* give you ownership
